### ISSUE TITLE
Issue Yarn Compilation + Server start

### ISSUE THREAD

**Issue by 777Bridges** [codedthemes/berry-free-react-admin-template#16]
Hello,

I tried to run the project on Macos BigSur 11.6 with those versions of plugins :
Node v14.18.3
Yarn v1.22.17

I have imported the GIT project in VSCode and then executed those commands
# yarn
I ve got this log 

Sebastiens-MacBook-Pro-2:react-ui sebastient$ yarn
yarn install v1.22.17
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "@emotion/styled > @emotion/babel-plugin@11.3.0" has unmet peer dependency "@babel/core@^7.0.0".
warning "@emotion/styled > @emotion/babel-plugin > @babel/plugin-syntax-jsx@7.12.13" has unmet peer dependency "@babel/core@^7.0.0-0".
warning " > @testing-library/user-event@12.8.3" has unmet peer dependency "@testing-library/dom@>=7.21.4".
warning "react-scripts > @typescript-eslint/eslint-plugin > tsutils@3.21.0" has unmet peer dependency "typescript@>=2.8.0  >= 3.2.0-dev  >= 3.3.0-dev  >= 3.4.0-dev  >= 3.5.0-dev  >= 3.6.0-dev  >= 3.6.0-beta  >= 3.7.0-dev  >= 3.7.0-beta".
warning "@material-ui/codemod > jscodeshift@0.13.0" has unmet peer dependency "@babel/preset-env@^7.1.6".
warning "@material-ui/codemod > jscodeshift-add-imports@1.0.10" has incorrect peer dependency "jscodeshift@^0.7.0  ^0.8.0  ^0.9.0  ^0.10.0  ^0.11.0".
warning "@material-ui/codemod > jscodeshift-add-imports > jscodeshift-find-imports@2.0.4" has incorrect peer dependency "jscodeshift@^0.7.0  ^0.8.0  ^0.9.0  ^0.10.0  ^0.11.0".
[--------------------------------------------------------------------------------------------------------------------------------------------------] 0/2143
**error** An unexpected error occurred: "ENOSYS: function not implemented, symlink '../../../parser/bin/babel-parser.js' -> '/Users/sebastient/pCloud Drive/My Documents/02_Pro/10_Trading/Flask_React/flask-react-berry-dashboard/react-ui/node_modules/@babel/core/node_modules/.bin/parser'".
info If you think this is a bug, please open a bug report with the information provided in "/Users/sebastient/pCloud Drive/My Documents/02_Pro/10_Trading/Flask_React/flask-react-berry-dashboard/react-ui/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

After I tried to launch the server
# yarn start
I ve got that error log

Failed to compile.

Failed to load plugin 'prettier' declared in '.eslintrc': Cannot find module 'eslint-plugin-prettier'
Require stack:
- /Users/sebastient/.config/yarn/global/node_modules/react-scripts/config/__placeholder__.js

I hope you will find a solution and will be able to help me

Thank you

**Comment by codedthemes** [comment]
This seems to be working fine for us. Have you changed yarn.lock file or any package?

![image](https://user-images.githubusercontent.com/32134933/151543723-671d9d76-214f-4737-8283-761b2c924b4d.png)

**Comment by app-generator** [comment]
Hello @777Bridges,

The problem might be related to the filesystem type of OS.
Basically, when Yarn tries to create a symlink for used packages, the OS bumps the` ENOSYS ..` error. 

This error is visible when the disk is formatted using `exFAT` and `FAT32`. 

Our advice is to format your working partition to `ext4` or something modern that supports symlinks.

**Comment by 777Bridges** [comment]
I checked my filesystem, it is APFS like the new generation of Mac.

**Comment by 777Bridges** [comment]
> This seems to be working fine for us. Have you changed yarn.lock file or any package?
> 
> ![image](https://user-images.githubusercontent.com/32134933/151543723-671d9d76-214f-4737-8283-761b2c924b4d.png)

Hello, 
thank you for your feedback. 
But it doesn't really help me. I see that your yarn project is building really quickly.
On my side it is so long, it is downloading like 80000 files and takes at least 1 hour to build...
Is that normal ?

**Comment by 777Bridges** [comment]
Good day,

I found the issue.
For all my project, I run it on a cloud server mount on my computer to be able to access to them everywhere. 
But for that project, it seems that it doesn't work.
Anyway, I tried to install everything locally and it works perfectkly.

Thank you for your help
