### ISSUE TITLE
There are no directories in pricing version

### ISSUE THREAD

**Issue by chulphan** [codedthemes/berry-free-react-admin-template#18]
views directory exists in demo version but not in standard+ version (next.js + typescript)
Can i get the views directory??

**Comment by codedthemes** [comment]
We have provided the next.js version as a Skeleton. So you integrate or start the new project quickly. 

As this issue is for the pro version.  We are closing here. You can contact our [support](https://codedthemes.support-hub.io/) team for further discussion.
