### ISSUE TITLE
#When I deploy to Netlify does not work

### ISSUE THREAD

**Issue by salemshah** [codedthemes/berry-free-react-admin-template#21]
locally it works fine but on netlify or heroku just a blank page, even though i didn't make any changes on any file

**Comment by codedthemes** [comment]
That is because the project is configured to deploy on a subdirectory.  I have created a branch for you without subdirectory deployment.

Branch: test-netifly

URL: https://6225e714bf71a00008bd4390--jolly-hawking-334284.netlify.app/
