### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by MihailButnaru** [codedthemes/berry-free-react-admin-template#25]
I am new to react js and i want to do a landing page.

Currently we have the APP that points to the Routes (dashboard)
```
        <StyledEngineProvider injectFirst>
            <ThemeProvider theme={theme(customization)}>
                <CssBaseline />
                <NavigationScroll>
                    <Routes />
                </NavigationScroll>
            </ThemeProvider>
        </StyledEngineProvider>
```
How can we have a landing page that will have the register/login and after that can redirect to the dashboard? Thank you

**Comment by codedthemes** [comment]
With the free version, the app will land to the dashboard. If you want to go to login first, you need to implement route guards. Route Guard will check if the user login or not and based on that redirect to the proper path. You may need to implement two route guard, Guest and Auth.

**Comment by codedthemes** [comment]
> 

Please create a separate issue for this.
