### ISSUE TITLE
Question: how can I change the redirect url when the login is successful?

### ISSUE THREAD

**Issue by MihailButnaru** [codedthemes/berry-free-react-admin-template#26]
At the moment it points to dashboard because of the default, my default is `Home` but when I log in it points to home, I want to change it to point to something else without changing the default url.
I am looking at the success but only see a dispatcher and submit. Any ideas, thank you

**Comment by MihailButnaru** [comment]
figured out by pushing to the new url. Another thing, after some time that I keep my frontend running I get blank page if I reload it later. Any ideas what can be the problem?

**Comment by codedthemes** [comment]
Glad you made it. Closing issue.
