### ISSUE TITLE
Question: Blank page

### ISSUE THREAD

**Issue by MihailButnaru** [codedthemes/berry-free-react-admin-template#35]
Hey Berry,

After running the app couple of times, I am getting blank page now. No errors in the console only 1 warning, any ideas what can be the reason?

**Comment by codedthemes** [comment]
Please share with us your working environment so we can evaluate the issue ASAP.
Node version 
NPM version
Console warning/errors if any

**Comment by codedthemes** [comment]
That would be a custom logic you need to implement.
