### ISSUE TITLE
Left menu collapses on refresh

### ISSUE THREAD

**Issue by AnithaKrypC** [codedthemes/berry-free-react-admin-template#40]
Left menu is collapsed on page refresh. Any suggestions or help?

**Comment by codedthemes** [comment]
Its not happening live, where did you found issue: https://berrydashboard.io/free/

**Comment by AnithaKrypC** [comment]
It's happening in live only. for instance , please go to this link https://berrydashboard.io/free/ and select _Tabler icons_ under **icons** menu. then refresh the page, it will collapse the **icons** menu.

**Comment by AnithaKrypC** [comment]
@codedthemes Hi , any help or suggestions for this  ?

**Comment by phoenixcoded20** [comment]
This is feature need to be implement. Looking for community.
