### ISSUE TITLE
Click not working in small media

### ISSUE THREAD

**Issue by phoenixcoded20** [codedthemes/berry-free-react-admin-template#53]
**Describe the bug**
Open site in mobile and try to open menu.

**To Reproduce**
Open site in mobile and try to open menu.

**Expected behavior**
It should open menu

**Screenshots**
N/A

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

-   Device: iPhoneX
-   OS: 15
-   Browser safari
-   Version 

**Additional context**

**Comment by Vitali883** [comment]
Not working on small screen for me as well. Chrome browser

**Comment by bierroma** [comment]
the same in any browser
