### ISSUE TITLE
Scrolling on mobile view in edge on login pages not possible

### ISSUE THREAD

**Issue by BennyAlex** [codedthemes/berry-free-react-admin-template#58]
**Describe the bug**
When visiting https://berrydashboard.io/free/pages/login/login3 on edge (for desktop) and using the dev tools to set the viewport to a smartphone, it's not possible to scroll down the page.
On firefox and on my real smartphone (chrome) it does work.

**Expected behavior**
Its possible to scroll to the rest of the page

**Screenshots**

**Desktop (please complete the following information):**

-   OS: [e.g. iOS] Win 11
-   Browser [e.g. chrome, safari] Edge
-   Version [e.g. 22] latest

**Comment by phoenixcoded20** [comment]
Hi,

Can you refresh page after setting media, and see if it works.

**Comment by phoenixcoded20** [comment]
This seems to be working. Closing as not reproducible.
