### ISSUE TITLE
404 page not working

### ISSUE THREAD

**Issue by gurusabarish** [codedthemes/berry-free-react-admin-template#6]
Hi @codedthemes 
You did really good job. I liked it <3

But, I faced an issue. When I enter a non routed page, I am not getting 404 page instead i got the default page. 

Thanks

![berry 404 error](https://user-images.githubusercontent.com/53465361/126281738-2ed3641c-22a1-47ec-ab32-aa125a5f2149.PNG)

**Comment by codedthemes** [comment]
That is because any unknown request will redirect to the default page. and the default page is the dashboard. Also, the free version is limited by features. There is no 404 page inside the code base.
