### ISSUE TITLE
Auto choose first option after clicking on dropdown (in sidebar)

### ISSUE THREAD

**Issue by GigaChad2137** [codedthemes/berry-free-react-admin-template#60]
I think this would be a pretty cool idea because I've encountered more than once that the name of a dropdown list is also the name of 1 option in it that could be selected automatically instead of forcing an extra click

**Comment by sreenathkumar** [comment]
can you please send any screenshots?

**Comment by GigaChad2137** [comment]
![obraz](https://user-images.githubusercontent.com/91125763/226282554-6a2ab93e-74e5-4565-bad5-21c1ac8d62f8.png)
 
 for example if you click Icons  it could open  Tabler icons
