### ISSUE TITLE
help wanted: Highlight only the selected menu item not the ListItem button when the LIST is open.

### ISSUE THREAD

**Issue by ankursehdev** [codedthemes/berry-free-react-admin-template#7]
Hello,

Thank you for the wonderful theme.

Currently, if a page/link/item is selected that will be highlighted, and if the List is open the background of the Button is set to be the same as the selected link. 

**How can I disable that highlighted background of the button if the list is only open, Only want that to be highlighted when the inner item is clicked/selected?**

For example here: 

I am on the Shadow Page and The ICONS list is only open, yet the background is the same as the selected page. 
I want the background of the list only to be active when the nested items of the list are selected.

![image](https://user-images.githubusercontent.com/34501847/129621035-3154ffd9-3b52-446d-9890-0610451450b4.png)

I want it like this: (done this using the inspect element)
Is there any simple solution to achieve this? I tried removing the SELECTED prop from the navCollapse but it removes the background from other items too.

![image](https://user-images.githubusercontent.com/34501847/129621395-001794cb-d2ee-459b-8cf8-a1c2d9c03d4b.png)

**Comment by codedthemes** [comment]
Hi, Thanks for the interest in berry. That is simple to achieve.

Just go to: 

> src\layout\MainLayout\Sidebar\MenuList\NavCollapse\index.js

 and change line 120 as following:


`className={level === 1 ? classes.listItemNoBack : classes.listItem}`


Only change is to replace > with ===.

![image](https://user-images.githubusercontent.com/32134933/129666311-6a09843b-234c-4f9e-a862-c40b8b837d4a.png)

**Comment by ankursehdev** [comment]
Thank you for the quick solution but I think this is going to create one more scenario, if the inner item is selected, and we close the collapse list. The top button won't be highlighted anymore. 

![image](https://user-images.githubusercontent.com/34501847/129772522-d4d94517-7ac6-4fbf-907f-9a0931ebe50d.png)

Although the Material-icon is selected but if I close the list the top list button is not highlighted, hence user won't know what part of the list this link is part of.

![image](https://user-images.githubusercontent.com/34501847/129772710-b9ab0c09-84ad-4c6f-a27e-30e8b29aee61.png)

Thanks for the help again.

**Comment by codedthemes** [comment]
Hi, I think at a certain point, it should be expected behavior, as if the user closing the menu, it means that the user no longer wants to see that list. You need to explore more in code and find a way out to solve as per your desired behavior. Let me know if you are stuck and need more help.
