### ISSUE TITLE
change "Twitter" to "𝕏 (Twitter)" In README.md Follow us Section

### ISSUE THREAD

**Issue by BandhiyaHardik** [codedthemes/berry-free-react-admin-template#77]
Twitter Badge is updated to new logo badge in README.md 

![image](https://github.com/codedthemes/berry-free-react-admin-template/assets/110784317/a34b229b-de0b-4a5f-afa4-67f9d1615135)

In Follow us section:

Currently:
![image](https://github.com/codedthemes/berry-free-react-admin-template/assets/110784317/2710d670-181a-4ba2-a79f-64f50825eb21)

Suggested Change:
![image](https://github.com/codedthemes/berry-free-react-admin-template/assets/110784317/5ff9236b-79ca-45bf-906a-c9ae352f36df)

**Comment by phoenixcoded20** [comment]
Done it other https://github.com/codedthemes/berry-free-react-admin-template/pull/80
